# Practica de Algebra lineal

### *Nombre*

<span style="color:blue">Ejercicio 1:  
Usando los procedimientos add y mult_vector_escalar definidos anteriormente, calcular:   
{$\alpha$[1,2]+[3,4] : $\alpha$$\in$$\mathbb{R}$, 0$\leq$$\alpha$$\leq$1, con una precision de dos decimales (para la multiplicación)}</style>

In [1]:
def addn(v,w):
    return[v[i]+w[i] for i in range(len(v))]

In [2]:
def mult_vector_escalar(alpha,v):
    return [round(alpha*v[i],2) for i in range(len(v))]

In [3]:
import numpy as np
v = [1,2]
w = [3,4]
for alpha in np.arange(0, 1.1, 0.1):
        print ("Para alpha = %.1f el resultado es:" % alpha)
        print(addn(mult_vector_escalar(alpha,v), w))

Para alpha = 0.0 el resultado es:
[3.0, 4.0]
Para alpha = 0.1 el resultado es:
[3.1, 4.2]
Para alpha = 0.2 el resultado es:
[3.2, 4.4]
Para alpha = 0.3 el resultado es:
[3.3, 4.6]
Para alpha = 0.4 el resultado es:
[3.4, 4.8]
Para alpha = 0.5 el resultado es:
[3.5, 5.0]
Para alpha = 0.6 el resultado es:
[3.6, 5.2]
Para alpha = 0.7 el resultado es:
[3.7, 5.4]
Para alpha = 0.8 el resultado es:
[3.8, 5.6]
Para alpha = 0.9 el resultado es:
[3.9, 5.8]
Para alpha = 1.0 el resultado es:
[4.0, 6.0]


<span style="color:blue">Ejercicio 2:  
Mortadelo y Filemón usan como clave el siguiente vector:</style>  
> <span style="color:blue">**k**=[0,1,0,0,1,0,1,0,1,0]</style>  

<span style="color:blue">Mortadelo quiere enviarle a Filemón el siguiente mensaje:</style>  
> <span style="color:blue">**p**=[0,0,0,1,1,1,0,1,0,1]</style>  

<span style="color:blue">Mortadelo encripta su mensaje añadiendo k:</style>  
> <span style="color:blue">**c**=**p**+**k**=[0,0,0,1,1,1,0,1,0,1]+[0,1,0,0,1,0,1,0,1,0]=[0,1,0,1,0,1,1,1,1,1]</style>  

<span style="color:blue">Cuando Filemón recibe el mensaje, lo desencripta añadiendo **k** a lo que ha recibido</style>  
> <span style="color:blue">**p**=**c**+**k**=[0,1,0,1,0,1,1,1,1,1]+[0,1,0,0,1,0,1,0,1,0]=[0,0,0,1,1,1,0,1,0,1]</style>    

<span style="color:blue">que es el mensaje original</style>    
  
 <span style="color:blue">¿Cómo lo harías en Python? (Definiendo un procedimiento)</style>  

In [4]:
def addGF2(a,b):
    if (a == b):
        return 0
    else:
        return (a+b)

In [5]:
def cryptoUtil(k,p):
    if(len(k) == len(p)):
        return [addGF2(k[i], p[i]) for i in range(len(p))]
    else:
        return "Error. No tienen la misma longitud"

In [6]:
k = [0,1,0,0,1,0,1,0,1,0]
p = [0,0,0,1,1,1,0,1,0,1]

In [7]:
# Mortadelo encripta su mensaje
c = cryptoUtil(k,p)
c

[0, 1, 0, 1, 0, 1, 1, 1, 1, 1]

In [8]:
# Filemon lo recibe, y lo desencripta
p = cryptoUtil(k,c)
p

[0, 0, 0, 1, 1, 1, 0, 1, 0, 1]

<span style="color:blue">Ejercicio 3: coste total o beneficio. </style>

<span style="color:blue">Supongamos que D es el conjunto de algunos ingredientes de la cerveza: </style>
> <span style="color:blue">D={lúpulo, malta, agua, levadura}</style>  

<span style="color:blue">Por otro lado tenemos el vector coste:</style>  
> <span style="color:blue">coste={lúpulo: 2,5€, malta: 1.5€, agua: 0.006€, levadura: 0,45€}</style>  

<span style="color:blue">Por último tenemos el vector cantidad con lo necesario para hacer una cerveza:</style>  
> <span style="color:blue">cantidad={lúpulo: 6u, malta: 14u, agua: 7u, levadura: 11u}</style>  

<span style="color:blue">¿Cuánto cuesta hacer una cerveza?</style> 

In [9]:
def producto_escalar(u,v):
    return sum(u[i]*v[i] for i in range(len(u)))

In [10]:
coste = [2.5, 1.5, 0.006, 0.45]
cantidad = [6,14,7,11]
costeCerveza = producto_escalar(coste, cantidad)
round(costeCerveza,2)

40.99

<span style="color:blue"> Ejercicio 4:   
¿Cómo escribirías cada uno de los vectores {[3,0,0],[0,2,0],[0,0,1]} como combinación lineal de {[2,0,1],[1,0,2],[2,2,2]}?
Escribe las combinaciones lineales en Python. Seguramente tenga que definir una nueva suma.</style>

In [11]:
def addn3(u,v,w):
    return[u[i]+v[i]+w[i] for i in range(len(u))]

In [12]:
# Siendo los vectores
u = [2,0,1]
v = [1,0,2]
w = [2,2,2]

In [13]:
# Para el primer vector ([3,0,0])
addn3(mult_vector_escalar(2,u), mult_vector_escalar(-1,v), mult_vector_escalar(0,w))

[3.0, 0.0, 0.0]

In [14]:
# Para el segundo vector ([0,2,0])
addn3(mult_vector_escalar(-0.666,u), mult_vector_escalar(-0.666,v), mult_vector_escalar(1,w))

[0.0, 2.0, 0.0]

In [15]:
# Para el tercer vector ([0,0,1])
addn3(mult_vector_escalar(-0.333,u), mult_vector_escalar(0.666,v), mult_vector_escalar(0,w))

[0.0, 0.0, 1.0]

<span style="color:blue"> Ejercicio 5:  
Dadas las matrices $
  A=
  \left[ {\begin{array}{cc}
   2 & -3 \\
   -4 & 6\\
  \end{array} } \right]
$ , $
  B=
  \left[ {\begin{array}{cc}
   8 & 4 \\
   5 & 5\\
  \end{array} } \right]
$
y $
  C=
  \left[ {\begin{array}{cc}
   5 & -2 \\
   3 & 1\\
  \end{array} } \right]
$, queremos verificar que AB=AC pero que B≠C.</style> 

In [16]:
import numpy as np
A = np.matrix([
    [2,-3],
    [-4,6]
])
B = np.matrix([
    [8,4],
    [5,5]
])
C = np.matrix([
    [5,-2],
    [3,1]
])

In [17]:
A*B

matrix([[ 1, -7],
        [-2, 14]])

In [18]:
A*C

matrix([[ 1, -7],
        [-2, 14]])

In [19]:
(B == C)

matrix([[False, False],
        [False, False]], dtype=bool)

<span style="color:blue"> Ejercicio 6 :  
Dadas la matriz $
  A=
  \left[ {\begin{array}{cc}
   3 & -6 \\
   -1 & 2\\
  \end{array} } \right]
$ , construye una matriz B de 2 × 2 tal que AB sea igual a la matriz cero. Las columnas de B no deben ser iguales entre sí y deben ser distintas de cero.
.</style> 

<span style="color:orange">
Debemos encontrar **B** = $
  \left[ {\begin{array}{cc}
   a & b \\
   c & d\\
  \end{array} } \right]
$ , tal que:  
$
  \left[ {\begin{array}{cc}
   3 & -6\\
   -1 & 2\\
  \end{array} } \right]
$  *  $
  \left[ {\begin{array}{cc}
   a & b\\
   c & d\\
  \end{array} } \right]
$ = $
  \left[ {\begin{array}{cc}
   0 & 0\\
   0 & 0\\
  \end{array} } \right]
$  </style>

<span style="color:orange">Por tanto, resolveremos el Sistema:</style>
> <span style="color:orange">3a - 6c = 0  </style>  
> <span style="color:orange">-a + 2c = 0  </style>  
> <span style="color:orange">3b - 6c = 0  </style>  
> <span style="color:orange">-b + 2d = 0  </style>  

In [20]:
import numpy as np
A = np.matrix([
    [3,0,-6,0],
    [-1,0,2,0],
    [0,3,0,-6],
    [0,-1,0,2]
])

np.linalg.matrix_rank(A)

2

In [21]:
AM = np.matrix([
    [3,0,-6,0,0],
    [-1,0,2,0,0],
    [0,3,0,-6,0],
    [0,-1,0,2,0]
])

np.linalg.matrix_rank(AM)

2

<span style="color:orange">Sistema Compatible Indeterminado (infinitas Soluciones).</style> 

In [22]:
from sympy import Matrix, solve_linear_system
from sympy.abc import a,b,c,d
AM = Matrix([
    [3,0,-6,0,0],
    [-1,0,2,0,0],
    [0,3,0,-6,0],
    [0,-1,0,2,0] 
])
solve_linear_system(AM,a,b,c,d)

{b: 2*d, a: 2*c}

<span style="color:orange">Si tomamos a = 4, nos queda que c = a / 2 = 4 / 2 = 2.</style>  
<span style="color:orange">Tomando b = 6, nos queda que d = b / 2 = 6 / 2 = 3.</style>  
<span style="color:orange">Con lo que B = $
  \left[ {\begin{array}{cc}
   4 & 6 \\
   2 & 3\\
  \end{array} } \right]
$</style>  

In [23]:
A = np.matrix([
    [3,-6],
    [-1,2]
])
B = np.matrix([
    [4,6],
    [2,3]
])

A*B

matrix([[0, 0],
        [0, 0]])

<span style="color:blue"> Ejercicio 7:  
Sarrus para el determinante de orden 3.  
¿Cómo lo haríamos en Python?</style>

In [24]:
def sarrus3(M):
    return M[0,0] * M[1,1] * M[2,2] + \
    M[0,1] * M[1,2] * M[2,0] + \
    M[1,0] * M[2,1] * M[0,2] - \
    (M[2,0] * M[1,1] * M[0,2] + \
     M[1,0] * M[0,1] * M[2,2] + \
     M[2,1] * M[1,2] * M[0,0]
    )

In [25]:
A = np.matrix([
    [1,0,1],
    [2,3,1],
    [2,1,1]
])
sarrus3(A)

-2

<span style="color:blue"> Ejercicio 8:  
Sabemos que hay un modo directo en Python para calcular los rangos. Calcula el número de soluciones de estos tres sistemas de ecuaciones empleándolo.</style> 

> <span style="color:blue">x<sub>1</sub> − 2x<sub>2</sub> + x<sub>3</sub> = 0 </style>  
> <span style="color:blue">2x<sub>2</sub>−8x<sub>3</sub>= 8  </style>  
> <span style="color:blue">−4x<sub>1</sub> + 5x<sub>2</sub> + 9x<sub>3</sub> =− 9</style>

In [26]:
import numpy as np
A1 = ([
    [1,-2,1],
    [0,2,-8],
    [-4,5,9]
])
np.linalg.matrix_rank(A1)

3

In [27]:
A1M = ([
    [1,-2,1,0],
    [0,2,-8,8],
    [-4,5,9,-9]
])
np.linalg.matrix_rank(A1M)

3

<span style="color:orange">Sistema Compatible Determinado con 3 Soluciones.</style>   

> <span style="color:blue">x<sub>2</sub> −4x<sub>3</sub> =8  </style>  
> <span style="color:blue">2x<sub>1</sub> −3x<sub>2</sub> + 2x<sub>3</sub> =1  </style>  
> <span style="color:blue">5x<sub>1</sub> −8x<sub>2</sub> + 7x<sub>3</sub> =1</style>

In [28]:
A2 = ([
    [0,1,-4],
    [2,-3,2],
    [5,-8,7]
])
np.linalg.matrix_rank(A2)

2

In [29]:
A2M = ([
    [0,1,-4,8],
    [2,-3,2,1],
    [5,-8,7,1]
])
np.linalg.matrix_rank(A2M)

3

<span style="color:orange">Sistema Incompatible (0 Soluciones).</style>   

> <span style="color:blue">x<sub>1</sub> +x<sub>3</sub> =2  </style>  
> <span style="color:blue">2x<sub>1</sub> +3x<sub>2</sub> + x<sub>3</sub> =3  </style>  
> <span style="color:blue">3x<sub>1</sub> +3x<sub>2</sub> + 2x<sub>3</sub> =5</style>

In [30]:
A3 = ([
    [1,0,1],
    [2,3,1],
    [3,3,2]
])
np.linalg.matrix_rank(A3)

2

In [31]:
A3M = ([
    [1,0,1,2],
    [2,3,1,3],
    [3,3,2,5]
])
np.linalg.matrix_rank(A3M)

2

<span style="color:orange">Sistema Compatible Indeterminado (infinitas Soluciones).</style>   

<span style="color:blue"> Ejercicio 9:  
Comprobar que r(x,y) para un ángulo $\theta$ es una función lineal.</style> 

<span style="color:orange">Tenemos que comprobar que:</style>  
* <span style="color:orange">Para cada vector v en V y cada escalar α en F, f (αv) = αf(v)</style>  
 <span style="color:orange">En nuestro caso, r(αx,αy) = (α$\cdot$cos($\theta$), α$\cdot$sen($\theta$)) 
= α$\cdot$(cos($\theta$), sen($\theta$))
= α$\cdot$r(x,y)  
</style>  
<span style="color:gray">Si, por ejemplo, $\theta$ = 90º, sabemos r([1,0]) = [0,1].  
Si tomamos α = 3, entonces tendriamos que:  
r(3x,3y) = (3$\cdot$cos(90º), 3$\cdot$sen(90º)) = (3$\cdot$0, 3$\cdot$1) = (0,3)   
Finalmente, 3$\cdot$(cos(90º), sen(90º)) = 3(0,1) = 3$\cdot$r(x,y) = (0,3)</style>  

* <span style="color:orange">Por cada dos vectores u y v en V, f (u + v) = f (u) + f (v)</style>  
<span style="color:orange">En nuestro caso, r([x<sub>1</sub>,y<sub>1</sub>] + [x<sub>2</sub>,y<sub>2</sub>]) =
r(x<sub>1</sub> + x<sub>2</sub>, y<sub>1</sub> + y<sub>2</sub>) =  
(cos($\theta$) - sen($\theta$), sen($\theta$) + cos($\theta$)) =  
(cos($\theta$), sen($\theta$)) + (-sen($\theta$) + cos($\theta$)) =  
r([x<sub>1</sub>,y<sub>1</sub>]) + r([x<sub>2</sub>,y<sub>2</sub>])  
</style>  
<span style="color:gray">Si, por ejemplo, $\theta$ = 90º, sabemos que:  
r([1,0]) = (cos(90º), sen(90º)) = [0,1]  
y que r([0,1]) = (-sen(90º), cos(90º)) = [-1,0]</style>  
<span style="color:gray">Por tanto: r([1,0] + [0,1]) = r(1+0, 0+1) =  
(cos(90º) - sen(90º), sen(90º) + cos(90º)) = (0-1, 1+0) = (-1,1)</style>  
<span style="color:gray">Finalmente:  
(cos(90º) - sen(90º), sen(90º) + cos(90º)) =  
(cos(90º), sen(90º)) + (-sen(90º), cos(90º)) = r([1,0]) + r([0,1)] =  
[0,1] + [-1,0] = (-1,1)</style>  

<span style="color:blue"> Ejercicio 10:  
¿Cuál es la representación coordenada del vector v= [6, 3, 2, 5] en términos de los vectores [2, 2, 2, 3], [1, 0, −1, 0], [0, 1, 0, 1]?</style> 

<span style="color:orange">Tenemos que resolver el Sistema:</style>
> <span style="color:orange">2x<sub>1</sub> + x<sub>2</sub> = 6  </style>  
> <span style="color:orange">2x<sub>1</sub> + x<sub>3</sub> = 3  </style>  
> <span style="color:orange">x<sub>1</sub> −x<sub>2</sub> = 2</style>  
> <span style="color:orange">3x<sub>1</sub> + x<sub>3</sub> = 5</style>

In [32]:
import numpy as np
A = np.matrix([
    [2,1,0],
    [2,0,1],
    [2,-1,0],
    [3,0,1]
])
np.linalg.matrix_rank(A)

3

<span style="color:orange">Como el rango es 3, descartamos la última ecuación (por ejemplo), y nos queda:</style>   
> <span style="color:orange">2x<sub>1</sub> + x<sub>2</sub> = 6  </style>  
> <span style="color:orange">2x<sub>1</sub> + x<sub>3</sub> = 3  </style>  
> <span style="color:orange">x<sub>1</sub> −x<sub>2</sub> = 2</style>  

In [33]:
AM = np.matrix([
    [2,1,0,6],
    [2,0,1,3],
    [2,-1,0,2]
])
np.linalg.matrix_rank(AM)

3

<span style="color:orange">Con lo que tenemos un Sistema Compatible Determinado con 3 Soluciones.</style>   

In [34]:
AR = np.matrix([
    [2,1,0],
    [2,0,1],
    [2,-1,0]
])
VR = np.matrix([
    [6],
    [3],
    [2]
])
np.linalg.solve(AR,VR)

matrix([[ 2.],
        [ 2.],
        [-1.]])

<span style="color:orange"> El vector v = [6,3,2,5] es igual a 2[2,2,2,3]+2[1,0,-1,0]-1[0,1,0,1].  
Por tanto, la representación en coordenadas de v en términos de los vectores [2,2,2,3],[1,0,-1,0],[0,1,0,1] es [2,2,-1]. </style>   

<span style="color:blue"> Ejercicio 11:  
Supongamos que queremos diseñar la red de internet para el otro campus universitario.  
La red debe lograr la misma conectividad que el grafo de entrada.  
Una arista representa un posible cable.  
El peso de la arista es el coste de instalar el cable.  
Nuestro objetivo es minimizar el coste total, usando el algoritmo Grow y el algoritmo Shrink.  </style> 

<span style="color:orange">
** Algoritmo Grow**</style>  
> <span style="color:orange"> def Grow (G)</style>  
> <span style="color:orange"> S: = ∅</style>
> <span style="color:orange"> Consideremos las aristas e en orden creciente:</style>  
>> <span style="color:orange"> Si los puntos finales de e aún no están conectados, agregue e a S.</style>  

<span style="color:orange"> Colocamos las aristas en orden creciente según sus pesos: 2,7,9.  
Cogemos la arista {Pembroke Campus, Bio-Med} y la añadimos a S.  
Hay que añadir el nodo Athletic Complex. Se puede hacer:</style>  
* <span style="color:orange">{Pembroke Campus, Athletic Complex}: 7</style>
* <span style="color:orange">{Bio-Med, Athletic Complex}: 9</style>  

<span style="color:orange">Luego añadimos a S la arista {Pembroke Campus, Athletic Complex}.  

<span style="color:orange">
Por tanto, el mínimo bosque generador del grafo quedaría:</style>  
> <span style="color:orange">S={ {Pembroke Campus, Bio-Med}, {Pembroke Campus, Athletic Complex} }</style>  

<span style="color:orange">** Algoritmo Shrink**</style>  
> <span style="color:orange"> def Shrink (G)</style>  
> <span style="color:orange"> S: = { {Pembroke Campus, Bio-Med}, {Bio-Med, Athletic Complex}, {Pembroke Campus, Athletic Complex} }</style>
> <span style="color:orange"> Consideremos las aristas e en orden decreciente:</style>  
>> <span style="color:orange"> Si cada par de nodos están conectados mediante S-{e}: quitar e de S.</style>  

<span style="color:orange"> Colocamos las aristas en orden decreciente según sus pesos: 9,7,2.  
La arista que más peso tiene es {Bio-Med, Athletic Complex}: 9. Si la quito aún podría seguir yendo de Bio-Med a Athletic Complex.  
Luego S= { {Pembroke Campus, Bio-Med}, {Pembroke Campus, Athletic Complex} }.  
La otras dos aristas restantes: {Pembroke Campus, Bio-Med} y {Pembroke Campus, Athletic Complex} no se pueden eliminar.  
Por tanto, finalmente queda S={ {Pembroke Campus, Bio-Med}, {Pembroke Campus, Athletic Complex} }.</style>  

<span style="color:blue"> Ejercicio 12:  
Sea la matriz $
  M=
  \left[ {\begin{array}{cc}
   1 & 0  & 0 & 5 \\
   0 & 2  & 0 & 7 \\
   0 & 0  & 3 & 9 \\
  \end{array} } \right]
$. Calcular el rango por filas y por columnas usando Python.</style> 

In [35]:
import numpy as np
M = np.matrix([
    [1,0,0,5],
    [0,2,0,7],
    [0,0,3,9]
])
rangoFilas = np.linalg.matrix_rank(M)
rangoFilas

3

In [36]:
rangoColumnas = np.linalg.matrix_rank(M.T)
rangoColumnas

3

<span style="color:blue"> Ejercicio 13 (opcional):  
Crea un algoritmo que transforme una matriz cualquiera en GF(2) en una matriz escalonada.</style> 

<span style="color:blue"> Ejercicio 14:  
Modificar lo necesario en los algoritmos para que funcionen y calculen el problema de la casa en llamas.</style>

In [37]:
import numpy as np

def producto_escalar(u,v):
    return sum(u[i]*v[i] for i in range(len(u)))

In [38]:
def proyeccion_paralela(b, a):
    sigma = (producto_escalar(b,a))/float((producto_escalar(a,a))) if (producto_escalar(a,a)) > 10^-20 else 0
    return [float(sigma) * a[i] for i in range(len(a))]

In [39]:
a=[6,2]
b=[2,4]
producto_escalar(a,a)
proyeccion_paralela(b,a)

[3.0, 1.0]

<span style="color:orange">Con lo que tenemos que el punto más cercano a **b** es [3,1].</style>   
<span style="color:orange">Ahora calculamos la proyección ortogonal b<sup>⊥a</sup>\.</style>   

In [40]:
def proyeccion_ortogonal(b, a):
    return [b[i] - proyeccion_paralela(b, a)[i] for i in range(len(b))]

In [41]:
proyeccion_ortogonal(b,a)

[-1.0, 3.0]

<span style="color:orange">Cuya norma es:</style>   

In [42]:
round(np.linalg.norm(proyeccion_ortogonal(b,a)),2)

3.16

<span style="color:orange">Por tanto, como la manguera mide 3.5, y la distancia a la casa es menor, podemos sofocar el incendio:</style>   

In [43]:
(np.linalg.norm(proyeccion_ortogonal(b,a)) < 3.5)

True